Support to_networkx(feature_name=None) to not include node features (#841)
Node features can be large, may not be always useful and have complicated types
(a ndarray or list). The latter can cause problems with some downstream
algorithms that cannot handle completely arbitrary attributes, like
`networkx.write_graphml`
<https://networkx.github.io/documentation/stable/reference/readwrite/generated/networkx.readwrite.graphml.write_graphml.html#networkx.readwrite.graphml.write_graphml>:

```
----> 2 nx.write_graphml(Gnx, os.path.join(dataset.data_directory, pred_fname))
[...]
NetworkXError: GraphML writer does not support <class 'list'> as data values.
```

```
----> 2 nx.write_graphml(Gnx, os.path.join(dataset.data_directory, pred_fname))
[...]
NetworkXError: GraphML writer does not support <class 'numpy.ndarray'> as data values.
```

This helps with some of our notebooks that use `networkx.write_graphml` (see:
#717).