Give nicer message for old NetworkX attribute on new StellarGraph (#680)
The StellarGraph type no longer inherits from the `networkx.MultiGraph` or
`networkx.MultiDiGraph` types. If a user updates to a new `stellargraph`
version, they may have code like `some_stellargraph.successors` that accesses
methods/properties on `StellarGraph` that were inherited from one of the
networkx super-classes, which will stop working with the new code, giving a
somewhat opaque error like:

```
AttributeError: 'StellarGraph' object has no attribute 'successors'
```

Fortunately, we can intercept the attribute look-up code path to put a more
helpful addition into the error message:

```
AttributeError: 'StellarGraph' object has no attribute 'successors'. The 'StellarGraph' type no longer inherits from NetworkX types: use a new StellarGraph method, or, if that is not possible, the `.to_networkx()` conversion function.
```