Add names to RGCN weights (#1677)
A Keras Layer with weights without names cannot be saved
(https://github.com/tensorflow/tensorflow/issues/36962), because an exception is
thrown:

```
AttributeError: 'NoneType' object has no attribute 'replace'
```

This PR adds names to the `add_weight` calls within
`RelationalGraphConvolution`, which were the only ones within all of
StellarGraph missing the `name=...` parameter.

This allows non-sparse RGCN models to be saved, but sparse ones still hit #1251.

See: #1252