Handle no edges in StellarGraph.create_graph_schema's np.unique calls (#867)
`numpy.unique` behaves poorly on a 2D array with a zero dimension when uniquing
whole rows (`axis=0`) instead of individual elements:

```python
>>> import numpy as np
>>> arr = np.zeros(shape=(0, 3))

>>> np.unique(arr) # individual elements is fine
array([], dtype=float64)

>>> np.unique(arr, axis=0) # whole rows is not
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<__array_function__ internals>", line 6, in unique
  File "/opt/anaconda3/lib/python3.7/site-packages/numpy/lib/arraysetops.py", line 274, in unique
    ar = ar.reshape(orig_shape[0], -1)
ValueError: cannot reshape array of size 0 into shape (0,newaxis)
```

This patch special-cases having no edges (which results in zero edge triples
(rows) being passed to `np.unique`).

See: https://github.com/numpy/numpy/issues/15559

See: #869